### ISSUE TITLE
`--reset` flag - Reboot a device connected via DFU.

### ISSUE THREAD

**Issue by cxnder** [hack-different/ipwndfu#33]
Might be helpful for tests, etc.

You can do this by requesting too much data with the hexdump read func, but there's probably a better way to implement it as well.

**Comment by rickmark** [comment]
Also noted the "RESET" and "DFU" ACC_IDs for Lightning are known (see `_data/lightning.yaml`) so full DFU + Exit is possible with the correct cable

**Comment by P5-2005** [comment]
> Might be helpful for tests, etc.
> 
> You can do this by requesting too much data with the hexdump read func, but there's probably a better way to implement it as well.
really this error kicked my iwatch s2 from dfu even was pwned, its like trick to exist dfu (reset) :D

```ipwndfu --patch-sigchecks
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ipwndfu", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipwndfu/main.py", line 132, in main
    patch_sigchecks(device, match_device=args.match_device)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipwndfu/main.py", line 591, in patch_sigchecks
    pwned.execute(0, trampoline_base + trampoline_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipwndfu/usbexec.py", line 317, in execute
    cmd += "\0" * 4
TypeError: can't concat str to bytes```
