### ISSUE TITLE
[Bug]: Error

### ISSUE THREAD

**Issue by 732502** [hack-different/ipwndfu#70]
### What device? (Specify CHIP/CPID)

7000

### What happened?

**Firstly this is actually the 7001, A8X Chip. I want to make this EXTREMELY clear. Its NOT the 7000, its the **7001.** 
**Firstly this is actually the 7001, A8X Chip. I want to make this EXTREMELY clear. Its NOT the 7000, its the **7001.** 
**Firstly this is actually the 7001, A8X Chip. I want to make this EXTREMELY clear. Its NOT the 7000, its the **7001.** 

So when I try to pwn my device, I get this error:   File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ipwndfu", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 117, in main
    pwn(device, match_device=args.match_device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 181, in pwn
    serial = get_serial(device.serial_number)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/usb/core.py", line 864, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/usb/util.py", line 313, in get_string
    raise ValueError("The device has no langid"
ValueError: The device has no langid (permission issue, no string descriptors supported or device error).

I was wondering if someone can help me with this or fix this.

### Version

Branch: Next

### What version of Python?

3.10

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ipwndfu", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 117, in main
    pwn(device, match_device=args.match_device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 181, in pwn
    serial = get_serial(device.serial_number)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/usb/core.py", line 864, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/usb/util.py", line 313, in get_string
    raise ValueError("The device has no langid"
ValueError: The device has no langid (permission issue, no string descriptors supported or device error)
```

### Sudo

- [X] I did run this as su or sudo

**Comment by Cryptiiiic** [comment]
Why would you put the log in your message and in log output?

**Comment by TheRealClarity** [comment]
Linux? MacOS? Host System (AMD/Intel/Mac)?

**Comment by 732502** [comment]
> Linux? MacOS? Host System (AMD/Intel/Mac)?

Mac

**Comment by TheRealClarity** [comment]
Please reboot your iPad and retry. It's been tested and confirmed working.

**Comment by TheRealClarity** [comment]
Closing due to lack of response, assuming user error.
