### ISSUE TITLE
[Bug]: NoBackendError for iPhone SE 2016

### ISSUE THREAD

**Issue by jonahdecker** [hack-different/ipwndfu#82]
### What device? (Specify CHIP/CPID)

8000

### What happened?

NoBackendError

### Version

v1.1

### What version of Python?

3.10

### Relevant log output

```shell
jonahdecker@Jonahs-MBP ipwndfu % sudo ipwndfu -p && ipwndfu --patch-sigchecks && ipwndfu --repair-heap
Password:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ipwndfu", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 121, in main
    pwn(device, match_device=args.match_device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/main.py", line 234, in pwn
    device = dfu.acquire_device(match=match_device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipwndfu/dfu.py", line 40, in acquire_device
    for device in usb.core.find(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
jonahdecker@Jonahs-MBP ipwndfu %
```

### Sudo

- [X] I did run this as su or sudo

**Comment by Cryptiiiic** [comment]
@jonahdecker this usually just means panic or usb corruption, likely because I never implemented repair heap for s8000
